import Vue from 'vue'
import Router from 'vue-router'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _7a6dbb4c = () => interopDefault(import('~/pages/dashboard/sales/index.vue' /* webpackChunkName: "" */))
const _6dfd381d = () => interopDefault(import('..\\pages\\Customers\\index.vue' /* webpackChunkName: "pages/Customers/index" */))
const _1217743c = () => interopDefault(import('..\\pages\\PurchaseOrders\\index.vue' /* webpackChunkName: "pages/PurchaseOrders/index" */))
const _1994113a = () => interopDefault(import('..\\pages\\widgets\\index.vue' /* webpackChunkName: "pages/widgets/index" */))
const _0f022b18 = () => interopDefault(import('..\\pages\\account\\forgot-password.vue' /* webpackChunkName: "pages/account/forgot-password" */))
const _701e843c = () => interopDefault(import('..\\pages\\account\\login.vue' /* webpackChunkName: "pages/account/login" */))
const _2d8f5b20 = () => interopDefault(import('..\\pages\\account\\register.vue' /* webpackChunkName: "pages/account/register" */))
const _7e9f3882 = () => interopDefault(import('..\\pages\\AccountManagement\\accountConfig.vue' /* webpackChunkName: "pages/AccountManagement/accountConfig" */))
const _282012b2 = () => interopDefault(import('..\\pages\\apps\\calendar\\index.vue' /* webpackChunkName: "pages/apps/calendar/index" */))
const _0407cd50 = () => interopDefault(import('..\\pages\\apps\\chat\\index.vue' /* webpackChunkName: "pages/apps/chat/index" */))
const _f6cedd6e = () => interopDefault(import('..\\pages\\apps\\Companies\\index.vue' /* webpackChunkName: "pages/apps/Companies/index" */))
const _6793bcee = () => interopDefault(import('..\\pages\\apps\\file-manager.vue' /* webpackChunkName: "pages/apps/file-manager" */))
const _12774bcb = () => interopDefault(import('..\\pages\\charts\\apex\\index.vue' /* webpackChunkName: "pages/charts/apex/index" */))
const _8bc1ae86 = () => interopDefault(import('..\\pages\\charts\\c3\\index.vue' /* webpackChunkName: "pages/charts/c3/index" */))
const _9beca57e = () => interopDefault(import('..\\pages\\charts\\chartist\\index.vue' /* webpackChunkName: "pages/charts/chartist/index" */))
const _0372c0c0 = () => interopDefault(import('..\\pages\\charts\\chartjs\\index.vue' /* webpackChunkName: "pages/charts/chartjs/index" */))
const _a7db17aa = () => interopDefault(import('..\\pages\\charts\\knob.vue' /* webpackChunkName: "pages/charts/knob" */))
const _a2b7525e = () => interopDefault(import('..\\pages\\contacts\\list.vue' /* webpackChunkName: "pages/contacts/list" */))
const _501f0346 = () => interopDefault(import('..\\pages\\contacts\\profile.vue' /* webpackChunkName: "pages/contacts/profile" */))
const _58949880 = () => interopDefault(import('..\\pages\\Customers\\data.js' /* webpackChunkName: "pages/Customers/data" */))
const _10e43530 = () => interopDefault(import('..\\pages\\dashboard\\analytics\\index.vue' /* webpackChunkName: "pages/dashboard/analytics/index" */))
const _0038fe50 = () => interopDefault(import('..\\pages\\dashboard\\crm\\index.vue' /* webpackChunkName: "pages/dashboard/crm/index" */))
const _18ccc42c = () => interopDefault(import('..\\pages\\dashboard\\sales\\index.vue' /* webpackChunkName: "pages/dashboard/sales/index" */))
const _2291cdf0 = () => interopDefault(import('..\\pages\\ecommerce\\cart.vue' /* webpackChunkName: "pages/ecommerce/cart" */))
const _2d4b7dd4 = () => interopDefault(import('..\\pages\\ecommerce\\checkout.vue' /* webpackChunkName: "pages/ecommerce/checkout" */))
const _ccadeeb0 = () => interopDefault(import('..\\pages\\ecommerce\\data-products.js' /* webpackChunkName: "pages/ecommerce/data-products" */))
const _38c99a80 = () => interopDefault(import('..\\pages\\ecommerce\\order-detail.vue' /* webpackChunkName: "pages/ecommerce/order-detail" */))
const _d77c3ca6 = () => interopDefault(import('..\\pages\\ecommerce\\orders\\index.vue' /* webpackChunkName: "pages/ecommerce/orders/index" */))
const _57bd436a = () => interopDefault(import('..\\pages\\ecommerce\\product-create.vue' /* webpackChunkName: "pages/ecommerce/product-create" */))
const _1205a864 = () => interopDefault(import('..\\pages\\ecommerce\\products\\index.vue' /* webpackChunkName: "pages/ecommerce/products/index" */))
const _6b12bbef = () => interopDefault(import('..\\pages\\ecommerce\\products-grid.vue' /* webpackChunkName: "pages/ecommerce/products-grid" */))
const _baade398 = () => interopDefault(import('..\\pages\\ecommerce\\sellers.vue' /* webpackChunkName: "pages/ecommerce/sellers" */))
const _805cb45c = () => interopDefault(import('..\\pages\\ecommerce\\Variant-product-create.vue' /* webpackChunkName: "pages/ecommerce/Variant-product-create" */))
const _56d01260 = () => interopDefault(import('..\\pages\\email\\data-inbox.js' /* webpackChunkName: "pages/email/data-inbox" */))
const _7553360a = () => interopDefault(import('..\\pages\\email\\inbox.vue' /* webpackChunkName: "pages/email/inbox" */))
const _b6cee5de = () => interopDefault(import('..\\pages\\email\\sidepanel.vue' /* webpackChunkName: "pages/email/sidepanel" */))
const _1c3d6f3d = () => interopDefault(import('..\\pages\\email\\templates.vue' /* webpackChunkName: "pages/email/templates" */))
const _3b925d02 = () => interopDefault(import('..\\pages\\email\\toolbar.vue' /* webpackChunkName: "pages/email/toolbar" */))
const _99712076 = () => interopDefault(import('..\\pages\\extras\\404.vue' /* webpackChunkName: "pages/extras/404" */))
const _119a71a1 = () => interopDefault(import('..\\pages\\extras\\404-alt.vue' /* webpackChunkName: "pages/extras/404-alt" */))
const _301565fc = () => interopDefault(import('..\\pages\\extras\\500.vue' /* webpackChunkName: "pages/extras/500" */))
const _22740ed4 = () => interopDefault(import('..\\pages\\extras\\coming-soon.vue' /* webpackChunkName: "pages/extras/coming-soon" */))
const _e9143a40 = () => interopDefault(import('..\\pages\\extras\\faqs.vue' /* webpackChunkName: "pages/extras/faqs" */))
const _b11c368c = () => interopDefault(import('..\\pages\\extras\\invoice.vue' /* webpackChunkName: "pages/extras/invoice" */))
const _6e04ba38 = () => interopDefault(import('..\\pages\\extras\\lightbox.vue' /* webpackChunkName: "pages/extras/lightbox" */))
const _59c66f20 = () => interopDefault(import('..\\pages\\extras\\maintenance.vue' /* webpackChunkName: "pages/extras/maintenance" */))
const _37b24cd3 = () => interopDefault(import('..\\pages\\extras\\pricing.vue' /* webpackChunkName: "pages/extras/pricing" */))
const _26bcd3d4 = () => interopDefault(import('..\\pages\\extras\\search-results.vue' /* webpackChunkName: "pages/extras/search-results" */))
const _4c674a42 = () => interopDefault(import('..\\pages\\extras\\sitemap.vue' /* webpackChunkName: "pages/extras/sitemap" */))
const _ebb53dc8 = () => interopDefault(import('..\\pages\\extras\\starter.vue' /* webpackChunkName: "pages/extras/starter" */))
const _4e0240f8 = () => interopDefault(import('..\\pages\\extras\\timeline.vue' /* webpackChunkName: "pages/extras/timeline" */))
const _73b4d7cc = () => interopDefault(import('..\\pages\\Finance\\BalanceTransaction.vue' /* webpackChunkName: "pages/Finance/BalanceTransaction" */))
const _35c06a1f = () => interopDefault(import('..\\pages\\Finance\\CompanyFile.vue' /* webpackChunkName: "pages/Finance/CompanyFile" */))
const _6c42ecd0 = () => interopDefault(import('..\\pages\\Finance\\Invoices.vue' /* webpackChunkName: "pages/Finance/Invoices" */))
const _f26544d2 = () => interopDefault(import('..\\pages\\Finance\\Payments.vue' /* webpackChunkName: "pages/Finance/Payments" */))
const _c3da5cbe = () => interopDefault(import('..\\pages\\forms\\advanced.vue' /* webpackChunkName: "pages/forms/advanced" */))
const _508c9014 = () => interopDefault(import('..\\pages\\forms\\elements.vue' /* webpackChunkName: "pages/forms/elements" */))
const _720bc5c0 = () => interopDefault(import('..\\pages\\forms\\file-uploads.vue' /* webpackChunkName: "pages/forms/file-uploads" */))
const _461c06eb = () => interopDefault(import('..\\pages\\forms\\mask.vue' /* webpackChunkName: "pages/forms/mask" */))
const _3fe4ced4 = () => interopDefault(import('..\\pages\\forms\\quill.vue' /* webpackChunkName: "pages/forms/quill" */))
const _542650b8 = () => interopDefault(import('..\\pages\\forms\\validation.vue' /* webpackChunkName: "pages/forms/validation" */))
const _d5649fac = () => interopDefault(import('..\\pages\\forms\\wizard.vue' /* webpackChunkName: "pages/forms/wizard" */))
const _674fb24e = () => interopDefault(import('..\\pages\\icons\\boxicons.vue' /* webpackChunkName: "pages/icons/boxicons" */))
const _665b14f4 = () => interopDefault(import('..\\pages\\icons\\data-fontawesome.js' /* webpackChunkName: "pages/icons/data-fontawesome" */))
const _a42bdf42 = () => interopDefault(import('..\\pages\\icons\\data-material.js' /* webpackChunkName: "pages/icons/data-material" */))
const _483b9f7f = () => interopDefault(import('..\\pages\\icons\\data-remix.js' /* webpackChunkName: "pages/icons/data-remix" */))
const _6b59602e = () => interopDefault(import('..\\pages\\icons\\feather.vue' /* webpackChunkName: "pages/icons/feather" */))
const _2db7978f = () => interopDefault(import('..\\pages\\icons\\font-awesome.vue' /* webpackChunkName: "pages/icons/font-awesome" */))
const _ef3c5710 = () => interopDefault(import('..\\pages\\icons\\mdi.vue' /* webpackChunkName: "pages/icons/mdi" */))
const _7cb8ff0f = () => interopDefault(import('..\\pages\\icons\\remix.vue' /* webpackChunkName: "pages/icons/remix" */))
const _a4f9a28c = () => interopDefault(import('..\\pages\\icons\\weather.vue' /* webpackChunkName: "pages/icons/weather" */))
const _700148db = () => interopDefault(import('..\\pages\\Inventory\\Inventory-list.vue' /* webpackChunkName: "pages/Inventory/Inventory-list" */))
const _7ed72f20 = () => interopDefault(import('..\\pages\\maps\\google.vue' /* webpackChunkName: "pages/maps/google" */))
const _33fd505f = () => interopDefault(import('..\\pages\\PurchaseOrders\\data.js' /* webpackChunkName: "pages/PurchaseOrders/data" */))
const _6e218036 = () => interopDefault(import('..\\pages\\PurchaseOrders\\order-detail.vue' /* webpackChunkName: "pages/PurchaseOrders/order-detail" */))
const _48dc3943 = () => interopDefault(import('..\\pages\\PurchaseOrders\\order-list.vue' /* webpackChunkName: "pages/PurchaseOrders/order-list" */))
const _1a6c45dc = () => interopDefault(import('..\\pages\\PurchaseOrders\\Purchase-create.vue' /* webpackChunkName: "pages/PurchaseOrders/Purchase-create" */))
const _dcc539fc = () => interopDefault(import('..\\pages\\SalesOrder\\pallet.vue' /* webpackChunkName: "pages/SalesOrder/pallet" */))
const _63d0d65f = () => interopDefault(import('..\\pages\\SalesOrder\\Sales-create.vue' /* webpackChunkName: "pages/SalesOrder/Sales-create" */))
const _0d5e087e = () => interopDefault(import('..\\pages\\SalesOrder\\Sales-list.vue' /* webpackChunkName: "pages/SalesOrder/Sales-list" */))
const _807e798a = () => interopDefault(import('..\\pages\\tables\\advanced\\index.vue' /* webpackChunkName: "pages/tables/advanced/index" */))
const _fe003d8e = () => interopDefault(import('..\\pages\\tables\\basic.vue' /* webpackChunkName: "pages/tables/basic" */))
const _3ace9076 = () => interopDefault(import('..\\pages\\task\\detail.vue' /* webpackChunkName: "pages/task/detail" */))
const _3f2e70a6 = () => interopDefault(import('..\\pages\\task\\kanban\\index.vue' /* webpackChunkName: "pages/task/kanban/index" */))
const _dbdf4cfa = () => interopDefault(import('..\\pages\\task\\list.vue' /* webpackChunkName: "pages/task/list" */))
const _4f5130b6 = () => interopDefault(import('..\\pages\\ui\\avatars.vue' /* webpackChunkName: "pages/ui/avatars" */))
const _6276eb06 = () => interopDefault(import('..\\pages\\ui\\buttons.vue' /* webpackChunkName: "pages/ui/buttons" */))
const _354ada5f = () => interopDefault(import('..\\pages\\ui\\cards.vue' /* webpackChunkName: "pages/ui/cards" */))
const _04e2bf94 = () => interopDefault(import('..\\pages\\ui\\carousel.vue' /* webpackChunkName: "pages/ui/carousel" */))
const _f4d61004 = () => interopDefault(import('..\\pages\\ui\\dropdowns.vue' /* webpackChunkName: "pages/ui/dropdowns" */))
const _6af9c864 = () => interopDefault(import('..\\pages\\ui\\general.vue' /* webpackChunkName: "pages/ui/general" */))
const _eeac970c = () => interopDefault(import('..\\pages\\ui\\grid.vue' /* webpackChunkName: "pages/ui/grid" */))
const _74f668a8 = () => interopDefault(import('..\\pages\\ui\\images.vue' /* webpackChunkName: "pages/ui/images" */))
const _62371bc4 = () => interopDefault(import('..\\pages\\ui\\list-group.vue' /* webpackChunkName: "pages/ui/list-group" */))
const _753904cc = () => interopDefault(import('..\\pages\\ui\\modals.vue' /* webpackChunkName: "pages/ui/modals" */))
const _056e1964 = () => interopDefault(import('..\\pages\\ui\\notifications.vue' /* webpackChunkName: "pages/ui/notifications" */))
const _01399b6d = () => interopDefault(import('..\\pages\\ui\\portlets.vue' /* webpackChunkName: "pages/ui/portlets" */))
const _6db81c3e = () => interopDefault(import('..\\pages\\ui\\progress.vue' /* webpackChunkName: "pages/ui/progress" */))
const _220d194e = () => interopDefault(import('..\\pages\\ui\\ribbons.vue' /* webpackChunkName: "pages/ui/ribbons" */))
const _695c52ae = () => interopDefault(import('..\\pages\\ui\\spinners.vue' /* webpackChunkName: "pages/ui/spinners" */))
const _77c67456 = () => interopDefault(import('..\\pages\\ui\\tabs-accordions.vue' /* webpackChunkName: "pages/ui/tabs-accordions" */))
const _69f20872 = () => interopDefault(import('..\\pages\\ui\\tooltips-popovers.vue' /* webpackChunkName: "pages/ui/tooltips-popovers" */))
const _4a9fdce3 = () => interopDefault(import('..\\pages\\ui\\typography.vue' /* webpackChunkName: "pages/ui/typography" */))
const _db648912 = () => interopDefault(import('..\\pages\\ui\\video.vue' /* webpackChunkName: "pages/ui/video" */))
const _3d3f1d74 = () => interopDefault(import('..\\pages\\widgets\\data.js' /* webpackChunkName: "pages/widgets/data" */))
const _a72ee1e4 = () => interopDefault(import('..\\pages\\apps\\calendar\\data-calendar.js' /* webpackChunkName: "pages/apps/calendar/data-calendar" */))
const _03c08c7b = () => interopDefault(import('..\\pages\\apps\\chat\\data.js' /* webpackChunkName: "pages/apps/chat/data" */))
const _036766a8 = () => interopDefault(import('..\\pages\\apps\\Companies\\data.js' /* webpackChunkName: "pages/apps/Companies/data" */))
const _6b8880a4 = () => interopDefault(import('..\\pages\\charts\\apex\\data.js' /* webpackChunkName: "pages/charts/apex/data" */))
const _508b9dc0 = () => interopDefault(import('..\\pages\\charts\\c3\\data.js' /* webpackChunkName: "pages/charts/c3/data" */))
const _6ac406a4 = () => interopDefault(import('..\\pages\\charts\\chartist\\data.js' /* webpackChunkName: "pages/charts/chartist/data" */))
const _3aff02ad = () => interopDefault(import('..\\pages\\charts\\chartjs\\BarChart.vue' /* webpackChunkName: "pages/charts/chartjs/BarChart" */))
const _712a5404 = () => interopDefault(import('..\\pages\\charts\\chartjs\\DonutChart.vue' /* webpackChunkName: "pages/charts/chartjs/DonutChart" */))
const _8ff57dd0 = () => interopDefault(import('..\\pages\\charts\\chartjs\\LineChart.vue' /* webpackChunkName: "pages/charts/chartjs/LineChart" */))
const _33be3558 = () => interopDefault(import('..\\pages\\charts\\chartjs\\PieChart.vue' /* webpackChunkName: "pages/charts/chartjs/PieChart" */))
const _7807b53c = () => interopDefault(import('..\\pages\\charts\\chartjs\\PolarChart.vue' /* webpackChunkName: "pages/charts/chartjs/PolarChart" */))
const _3f00329a = () => interopDefault(import('..\\pages\\charts\\chartjs\\RadarChart.vue' /* webpackChunkName: "pages/charts/chartjs/RadarChart" */))
const _cf93c43c = () => interopDefault(import('..\\pages\\dashboard\\analytics\\channels.vue' /* webpackChunkName: "pages/dashboard/analytics/channels" */))
const _422beb0b = () => interopDefault(import('..\\pages\\dashboard\\analytics\\overview.vue' /* webpackChunkName: "pages/dashboard/analytics/overview" */))
const _76bd4896 = () => interopDefault(import('..\\pages\\dashboard\\analytics\\social-media.vue' /* webpackChunkName: "pages/dashboard/analytics/social-media" */))
const _538c2b96 = () => interopDefault(import('..\\pages\\dashboard\\analytics\\sources.vue' /* webpackChunkName: "pages/dashboard/analytics/sources" */))
const _564e0f66 = () => interopDefault(import('..\\pages\\dashboard\\analytics\\users.vue' /* webpackChunkName: "pages/dashboard/analytics/users" */))
const _58166610 = () => interopDefault(import('..\\pages\\ecommerce\\orders\\data.js' /* webpackChunkName: "pages/ecommerce/orders/data" */))
const _3bafc471 = () => interopDefault(import('..\\pages\\ecommerce\\products\\data.js' /* webpackChunkName: "pages/ecommerce/products/data" */))
const _1d495e03 = () => interopDefault(import('..\\pages\\Finance\\Expenses\\Expense.vue' /* webpackChunkName: "pages/Finance/Expenses/Expense" */))
const _757843d6 = () => interopDefault(import('..\\pages\\Finance\\Expenses\\list-Expenses.vue' /* webpackChunkName: "pages/Finance/Expenses/list-Expenses" */))
const _854759c4 = () => interopDefault(import('..\\pages\\tables\\advanced\\data.js' /* webpackChunkName: "pages/tables/advanced/data" */))
const _0c9c5f49 = () => interopDefault(import('..\\pages\\task\\kanban\\data.js' /* webpackChunkName: "pages/task/kanban/data" */))
const _890c52ea = () => interopDefault(import('..\\pages\\ecommerce\\product-detail\\_id.vue' /* webpackChunkName: "pages/ecommerce/product-detail/_id" */))
const _2e293060 = () => interopDefault(import('..\\pages\\email\\reademail\\_id.vue' /* webpackChunkName: "pages/email/reademail/_id" */))

// TODO: remove in Nuxt 3
const emptyFn = () => {}
const originalPush = Router.prototype.push
Router.prototype.push = function push (location, onComplete = emptyFn, onAbort) {
  return originalPush.call(this, location, onComplete, onAbort)
}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: decodeURI('/'),
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/ar",
    component: _7a6dbb4c
  }, {
    path: "/Customers",
    component: _6dfd381d,
    name: "Customers___en"
  }, {
    path: "/es",
    component: _7a6dbb4c
  }, {
    path: "/fr",
    component: _7a6dbb4c
  }, {
    path: "/PurchaseOrders",
    component: _1217743c,
    name: "PurchaseOrders___en"
  }, {
    path: "/widgets",
    component: _1994113a,
    name: "widgets___en"
  }, {
    path: "/account/forgot-password",
    component: _0f022b18,
    name: "account-forgot-password___en"
  }, {
    path: "/account/login",
    component: _701e843c,
    name: "account-login___en"
  }, {
    path: "/account/register",
    component: _2d8f5b20,
    name: "account-register___en"
  }, {
    path: "/AccountManagement/accountConfig",
    component: _7e9f3882,
    name: "AccountManagement-accountConfig___en"
  }, {
    path: "/apps/calendar",
    component: _282012b2,
    name: "apps-calendar___en"
  }, {
    path: "/apps/chat",
    component: _0407cd50,
    name: "apps-chat___en"
  }, {
    path: "/apps/Companies",
    component: _f6cedd6e,
    name: "apps-Companies___en"
  }, {
    path: "/apps/file-manager",
    component: _6793bcee,
    name: "apps-file-manager___en"
  }, {
    path: "/ar/Customers",
    component: _6dfd381d,
    name: "Customers___ar"
  }, {
    path: "/ar/PurchaseOrders",
    component: _1217743c,
    name: "PurchaseOrders___ar"
  }, {
    path: "/ar/widgets",
    component: _1994113a,
    name: "widgets___ar"
  }, {
    path: "/charts/apex",
    component: _12774bcb,
    name: "charts-apex___en"
  }, {
    path: "/charts/c3",
    component: _8bc1ae86,
    name: "charts-c3___en"
  }, {
    path: "/charts/chartist",
    component: _9beca57e,
    name: "charts-chartist___en"
  }, {
    path: "/charts/chartjs",
    component: _0372c0c0,
    name: "charts-chartjs___en"
  }, {
    path: "/charts/knob",
    component: _a7db17aa,
    name: "charts-knob___en"
  }, {
    path: "/contacts/list",
    component: _a2b7525e,
    name: "contacts-list___en"
  }, {
    path: "/contacts/profile",
    component: _501f0346,
    name: "contacts-profile___en"
  }, {
    path: "/Customers/data",
    component: _58949880,
    name: "Customers-data___en"
  }, {
    path: "/dashboard/analytics",
    component: _10e43530,
    name: "dashboard-analytics___en"
  }, {
    path: "/dashboard/crm",
    component: _0038fe50,
    name: "dashboard-crm___en"
  }, {
    path: "/dashboard/sales",
    component: _18ccc42c,
    name: "dashboard-sales___en"
  }, {
    path: "/ecommerce/cart",
    component: _2291cdf0,
    name: "ecommerce-cart___en"
  }, {
    path: "/ecommerce/checkout",
    component: _2d4b7dd4,
    name: "ecommerce-checkout___en"
  }, {
    path: "/ecommerce/data-products",
    component: _ccadeeb0,
    name: "ecommerce-data-products___en"
  }, {
    path: "/ecommerce/order-detail",
    component: _38c99a80,
    name: "ecommerce-order-detail___en"
  }, {
    path: "/ecommerce/orders",
    component: _d77c3ca6,
    name: "ecommerce-orders___en"
  }, {
    path: "/ecommerce/product-create",
    component: _57bd436a,
    name: "ecommerce-product-create___en"
  }, {
    path: "/ecommerce/products",
    component: _1205a864,
    name: "ecommerce-products___en"
  }, {
    path: "/ecommerce/products-grid",
    component: _6b12bbef,
    name: "ecommerce-products-grid___en"
  }, {
    path: "/ecommerce/sellers",
    component: _baade398,
    name: "ecommerce-sellers___en"
  }, {
    path: "/ecommerce/Variant-product-create",
    component: _805cb45c,
    name: "ecommerce-Variant-product-create___en"
  }, {
    path: "/email/data-inbox",
    component: _56d01260,
    name: "email-data-inbox___en"
  }, {
    path: "/email/inbox",
    component: _7553360a,
    name: "email-inbox___en"
  }, {
    path: "/email/sidepanel",
    component: _b6cee5de,
    name: "email-sidepanel___en"
  }, {
    path: "/email/templates",
    component: _1c3d6f3d,
    name: "email-templates___en"
  }, {
    path: "/email/toolbar",
    component: _3b925d02,
    name: "email-toolbar___en"
  }, {
    path: "/es/Customers",
    component: _6dfd381d,
    name: "Customers___es"
  }, {
    path: "/es/PurchaseOrders",
    component: _1217743c,
    name: "PurchaseOrders___es"
  }, {
    path: "/es/widgets",
    component: _1994113a,
    name: "widgets___es"
  }, {
    path: "/extras/404",
    component: _99712076,
    name: "extras-404___en"
  }, {
    path: "/extras/404-alt",
    component: _119a71a1,
    name: "extras-404-alt___en"
  }, {
    path: "/extras/500",
    component: _301565fc,
    name: "extras-500___en"
  }, {
    path: "/extras/coming-soon",
    component: _22740ed4,
    name: "extras-coming-soon___en"
  }, {
    path: "/extras/faqs",
    component: _e9143a40,
    name: "extras-faqs___en"
  }, {
    path: "/extras/invoice",
    component: _b11c368c,
    name: "extras-invoice___en"
  }, {
    path: "/extras/lightbox",
    component: _6e04ba38,
    name: "extras-lightbox___en"
  }, {
    path: "/extras/maintenance",
    component: _59c66f20,
    name: "extras-maintenance___en"
  }, {
    path: "/extras/pricing",
    component: _37b24cd3,
    name: "extras-pricing___en"
  }, {
    path: "/extras/search-results",
    component: _26bcd3d4,
    name: "extras-search-results___en"
  }, {
    path: "/extras/sitemap",
    component: _4c674a42,
    name: "extras-sitemap___en"
  }, {
    path: "/extras/starter",
    component: _ebb53dc8,
    name: "extras-starter___en"
  }, {
    path: "/extras/timeline",
    component: _4e0240f8,
    name: "extras-timeline___en"
  }, {
    path: "/Finance/BalanceTransaction",
    component: _73b4d7cc,
    name: "Finance-BalanceTransaction___en"
  }, {
    path: "/Finance/CompanyFile",
    component: _35c06a1f,
    name: "Finance-CompanyFile___en"
  }, {
    path: "/Finance/Invoices",
    component: _6c42ecd0,
    name: "Finance-Invoices___en"
  }, {
    path: "/Finance/Payments",
    component: _f26544d2,
    name: "Finance-Payments___en"
  }, {
    path: "/forms/advanced",
    component: _c3da5cbe,
    name: "forms-advanced___en"
  }, {
    path: "/forms/elements",
    component: _508c9014,
    name: "forms-elements___en"
  }, {
    path: "/forms/file-uploads",
    component: _720bc5c0,
    name: "forms-file-uploads___en"
  }, {
    path: "/forms/mask",
    component: _461c06eb,
    name: "forms-mask___en"
  }, {
    path: "/forms/quill",
    component: _3fe4ced4,
    name: "forms-quill___en"
  }, {
    path: "/forms/validation",
    component: _542650b8,
    name: "forms-validation___en"
  }, {
    path: "/forms/wizard",
    component: _d5649fac,
    name: "forms-wizard___en"
  }, {
    path: "/fr/Customers",
    component: _6dfd381d,
    name: "Customers___fr"
  }, {
    path: "/fr/PurchaseOrders",
    component: _1217743c,
    name: "PurchaseOrders___fr"
  }, {
    path: "/fr/widgets",
    component: _1994113a,
    name: "widgets___fr"
  }, {
    path: "/icons/boxicons",
    component: _674fb24e,
    name: "icons-boxicons___en"
  }, {
    path: "/icons/data-fontawesome",
    component: _665b14f4,
    name: "icons-data-fontawesome___en"
  }, {
    path: "/icons/data-material",
    component: _a42bdf42,
    name: "icons-data-material___en"
  }, {
    path: "/icons/data-remix",
    component: _483b9f7f,
    name: "icons-data-remix___en"
  }, {
    path: "/icons/feather",
    component: _6b59602e,
    name: "icons-feather___en"
  }, {
    path: "/icons/font-awesome",
    component: _2db7978f,
    name: "icons-font-awesome___en"
  }, {
    path: "/icons/mdi",
    component: _ef3c5710,
    name: "icons-mdi___en"
  }, {
    path: "/icons/remix",
    component: _7cb8ff0f,
    name: "icons-remix___en"
  }, {
    path: "/icons/weather",
    component: _a4f9a28c,
    name: "icons-weather___en"
  }, {
    path: "/Inventory/Inventory-list",
    component: _700148db,
    name: "Inventory-Inventory-list___en"
  }, {
    path: "/maps/google",
    component: _7ed72f20,
    name: "maps-google___en"
  }, {
    path: "/PurchaseOrders/data",
    component: _33fd505f,
    name: "PurchaseOrders-data___en"
  }, {
    path: "/PurchaseOrders/order-detail",
    component: _6e218036,
    name: "PurchaseOrders-order-detail___en"
  }, {
    path: "/PurchaseOrders/order-list",
    component: _48dc3943,
    name: "PurchaseOrders-order-list___en"
  }, {
    path: "/PurchaseOrders/Purchase-create",
    component: _1a6c45dc,
    name: "PurchaseOrders-Purchase-create___en"
  }, {
    path: "/SalesOrder/pallet",
    component: _dcc539fc,
    name: "SalesOrder-pallet___en"
  }, {
    path: "/SalesOrder/Sales-create",
    component: _63d0d65f,
    name: "SalesOrder-Sales-create___en"
  }, {
    path: "/SalesOrder/Sales-list",
    component: _0d5e087e,
    name: "SalesOrder-Sales-list___en"
  }, {
    path: "/tables/advanced",
    component: _807e798a,
    name: "tables-advanced___en"
  }, {
    path: "/tables/basic",
    component: _fe003d8e,
    name: "tables-basic___en"
  }, {
    path: "/task/detail",
    component: _3ace9076,
    name: "task-detail___en"
  }, {
    path: "/task/kanban",
    component: _3f2e70a6,
    name: "task-kanban___en"
  }, {
    path: "/task/list",
    component: _dbdf4cfa,
    name: "task-list___en"
  }, {
    path: "/ui/avatars",
    component: _4f5130b6,
    name: "ui-avatars___en"
  }, {
    path: "/ui/buttons",
    component: _6276eb06,
    name: "ui-buttons___en"
  }, {
    path: "/ui/cards",
    component: _354ada5f,
    name: "ui-cards___en"
  }, {
    path: "/ui/carousel",
    component: _04e2bf94,
    name: "ui-carousel___en"
  }, {
    path: "/ui/dropdowns",
    component: _f4d61004,
    name: "ui-dropdowns___en"
  }, {
    path: "/ui/general",
    component: _6af9c864,
    name: "ui-general___en"
  }, {
    path: "/ui/grid",
    component: _eeac970c,
    name: "ui-grid___en"
  }, {
    path: "/ui/images",
    component: _74f668a8,
    name: "ui-images___en"
  }, {
    path: "/ui/list-group",
    component: _62371bc4,
    name: "ui-list-group___en"
  }, {
    path: "/ui/modals",
    component: _753904cc,
    name: "ui-modals___en"
  }, {
    path: "/ui/notifications",
    component: _056e1964,
    name: "ui-notifications___en"
  }, {
    path: "/ui/portlets",
    component: _01399b6d,
    name: "ui-portlets___en"
  }, {
    path: "/ui/progress",
    component: _6db81c3e,
    name: "ui-progress___en"
  }, {
    path: "/ui/ribbons",
    component: _220d194e,
    name: "ui-ribbons___en"
  }, {
    path: "/ui/spinners",
    component: _695c52ae,
    name: "ui-spinners___en"
  }, {
    path: "/ui/tabs-accordions",
    component: _77c67456,
    name: "ui-tabs-accordions___en"
  }, {
    path: "/ui/tooltips-popovers",
    component: _69f20872,
    name: "ui-tooltips-popovers___en"
  }, {
    path: "/ui/typography",
    component: _4a9fdce3,
    name: "ui-typography___en"
  }, {
    path: "/ui/video",
    component: _db648912,
    name: "ui-video___en"
  }, {
    path: "/widgets/data",
    component: _3d3f1d74,
    name: "widgets-data___en"
  }, {
    path: "/apps/calendar/data-calendar",
    component: _a72ee1e4,
    name: "apps-calendar-data-calendar___en"
  }, {
    path: "/apps/chat/data",
    component: _03c08c7b,
    name: "apps-chat-data___en"
  }, {
    path: "/apps/Companies/data",
    component: _036766a8,
    name: "apps-Companies-data___en"
  }, {
    path: "/ar/account/forgot-password",
    component: _0f022b18,
    name: "account-forgot-password___ar"
  }, {
    path: "/ar/account/login",
    component: _701e843c,
    name: "account-login___ar"
  }, {
    path: "/ar/account/register",
    component: _2d8f5b20,
    name: "account-register___ar"
  }, {
    path: "/ar/AccountManagement/accountConfig",
    component: _7e9f3882,
    name: "AccountManagement-accountConfig___ar"
  }, {
    path: "/ar/apps/calendar",
    component: _282012b2,
    name: "apps-calendar___ar"
  }, {
    path: "/ar/apps/chat",
    component: _0407cd50,
    name: "apps-chat___ar"
  }, {
    path: "/ar/apps/Companies",
    component: _f6cedd6e,
    name: "apps-Companies___ar"
  }, {
    path: "/ar/apps/file-manager",
    component: _6793bcee,
    name: "apps-file-manager___ar"
  }, {
    path: "/ar/charts/apex",
    component: _12774bcb,
    name: "charts-apex___ar"
  }, {
    path: "/ar/charts/c3",
    component: _8bc1ae86,
    name: "charts-c3___ar"
  }, {
    path: "/ar/charts/chartist",
    component: _9beca57e,
    name: "charts-chartist___ar"
  }, {
    path: "/ar/charts/chartjs",
    component: _0372c0c0,
    name: "charts-chartjs___ar"
  }, {
    path: "/ar/charts/knob",
    component: _a7db17aa,
    name: "charts-knob___ar"
  }, {
    path: "/ar/contacts/list",
    component: _a2b7525e,
    name: "contacts-list___ar"
  }, {
    path: "/ar/contacts/profile",
    component: _501f0346,
    name: "contacts-profile___ar"
  }, {
    path: "/ar/Customers/data",
    component: _58949880,
    name: "Customers-data___ar"
  }, {
    path: "/ar/dashboard/analytics",
    component: _10e43530,
    name: "dashboard-analytics___ar"
  }, {
    path: "/ar/dashboard/crm",
    component: _0038fe50,
    name: "dashboard-crm___ar"
  }, {
    path: "/ar/dashboard/sales",
    component: _18ccc42c,
    name: "dashboard-sales___ar"
  }, {
    path: "/ar/ecommerce/cart",
    component: _2291cdf0,
    name: "ecommerce-cart___ar"
  }, {
    path: "/ar/ecommerce/checkout",
    component: _2d4b7dd4,
    name: "ecommerce-checkout___ar"
  }, {
    path: "/ar/ecommerce/data-products",
    component: _ccadeeb0,
    name: "ecommerce-data-products___ar"
  }, {
    path: "/ar/ecommerce/order-detail",
    component: _38c99a80,
    name: "ecommerce-order-detail___ar"
  }, {
    path: "/ar/ecommerce/orders",
    component: _d77c3ca6,
    name: "ecommerce-orders___ar"
  }, {
    path: "/ar/ecommerce/product-create",
    component: _57bd436a,
    name: "ecommerce-product-create___ar"
  }, {
    path: "/ar/ecommerce/products",
    component: _1205a864,
    name: "ecommerce-products___ar"
  }, {
    path: "/ar/ecommerce/products-grid",
    component: _6b12bbef,
    name: "ecommerce-products-grid___ar"
  }, {
    path: "/ar/ecommerce/sellers",
    component: _baade398,
    name: "ecommerce-sellers___ar"
  }, {
    path: "/ar/ecommerce/Variant-product-create",
    component: _805cb45c,
    name: "ecommerce-Variant-product-create___ar"
  }, {
    path: "/ar/email/data-inbox",
    component: _56d01260,
    name: "email-data-inbox___ar"
  }, {
    path: "/ar/email/inbox",
    component: _7553360a,
    name: "email-inbox___ar"
  }, {
    path: "/ar/email/sidepanel",
    component: _b6cee5de,
    name: "email-sidepanel___ar"
  }, {
    path: "/ar/email/templates",
    component: _1c3d6f3d,
    name: "email-templates___ar"
  }, {
    path: "/ar/email/toolbar",
    component: _3b925d02,
    name: "email-toolbar___ar"
  }, {
    path: "/ar/extras/404",
    component: _99712076,
    name: "extras-404___ar"
  }, {
    path: "/ar/extras/404-alt",
    component: _119a71a1,
    name: "extras-404-alt___ar"
  }, {
    path: "/ar/extras/500",
    component: _301565fc,
    name: "extras-500___ar"
  }, {
    path: "/ar/extras/coming-soon",
    component: _22740ed4,
    name: "extras-coming-soon___ar"
  }, {
    path: "/ar/extras/faqs",
    component: _e9143a40,
    name: "extras-faqs___ar"
  }, {
    path: "/ar/extras/invoice",
    component: _b11c368c,
    name: "extras-invoice___ar"
  }, {
    path: "/ar/extras/lightbox",
    component: _6e04ba38,
    name: "extras-lightbox___ar"
  }, {
    path: "/ar/extras/maintenance",
    component: _59c66f20,
    name: "extras-maintenance___ar"
  }, {
    path: "/ar/extras/pricing",
    component: _37b24cd3,
    name: "extras-pricing___ar"
  }, {
    path: "/ar/extras/search-results",
    component: _26bcd3d4,
    name: "extras-search-results___ar"
  }, {
    path: "/ar/extras/sitemap",
    component: _4c674a42,
    name: "extras-sitemap___ar"
  }, {
    path: "/ar/extras/starter",
    component: _ebb53dc8,
    name: "extras-starter___ar"
  }, {
    path: "/ar/extras/timeline",
    component: _4e0240f8,
    name: "extras-timeline___ar"
  }, {
    path: "/ar/Finance/BalanceTransaction",
    component: _73b4d7cc,
    name: "Finance-BalanceTransaction___ar"
  }, {
    path: "/ar/Finance/CompanyFile",
    component: _35c06a1f,
    name: "Finance-CompanyFile___ar"
  }, {
    path: "/ar/Finance/Invoices",
    component: _6c42ecd0,
    name: "Finance-Invoices___ar"
  }, {
    path: "/ar/Finance/Payments",
    component: _f26544d2,
    name: "Finance-Payments___ar"
  }, {
    path: "/ar/forms/advanced",
    component: _c3da5cbe,
    name: "forms-advanced___ar"
  }, {
    path: "/ar/forms/elements",
    component: _508c9014,
    name: "forms-elements___ar"
  }, {
    path: "/ar/forms/file-uploads",
    component: _720bc5c0,
    name: "forms-file-uploads___ar"
  }, {
    path: "/ar/forms/mask",
    component: _461c06eb,
    name: "forms-mask___ar"
  }, {
    path: "/ar/forms/quill",
    component: _3fe4ced4,
    name: "forms-quill___ar"
  }, {
    path: "/ar/forms/validation",
    component: _542650b8,
    name: "forms-validation___ar"
  }, {
    path: "/ar/forms/wizard",
    component: _d5649fac,
    name: "forms-wizard___ar"
  }, {
    path: "/ar/icons/boxicons",
    component: _674fb24e,
    name: "icons-boxicons___ar"
  }, {
    path: "/ar/icons/data-fontawesome",
    component: _665b14f4,
    name: "icons-data-fontawesome___ar"
  }, {
    path: "/ar/icons/data-material",
    component: _a42bdf42,
    name: "icons-data-material___ar"
  }, {
    path: "/ar/icons/data-remix",
    component: _483b9f7f,
    name: "icons-data-remix___ar"
  }, {
    path: "/ar/icons/feather",
    component: _6b59602e,
    name: "icons-feather___ar"
  }, {
    path: "/ar/icons/font-awesome",
    component: _2db7978f,
    name: "icons-font-awesome___ar"
  }, {
    path: "/ar/icons/mdi",
    component: _ef3c5710,
    name: "icons-mdi___ar"
  }, {
    path: "/ar/icons/remix",
    component: _7cb8ff0f,
    name: "icons-remix___ar"
  }, {
    path: "/ar/icons/weather",
    component: _a4f9a28c,
    name: "icons-weather___ar"
  }, {
    path: "/ar/Inventory/Inventory-list",
    component: _700148db,
    name: "Inventory-Inventory-list___ar"
  }, {
    path: "/ar/maps/google",
    component: _7ed72f20,
    name: "maps-google___ar"
  }, {
    path: "/ar/PurchaseOrders/data",
    component: _33fd505f,
    name: "PurchaseOrders-data___ar"
  }, {
    path: "/ar/PurchaseOrders/order-detail",
    component: _6e218036,
    name: "PurchaseOrders-order-detail___ar"
  }, {
    path: "/ar/PurchaseOrders/order-list",
    component: _48dc3943,
    name: "PurchaseOrders-order-list___ar"
  }, {
    path: "/ar/PurchaseOrders/Purchase-create",
    component: _1a6c45dc,
    name: "PurchaseOrders-Purchase-create___ar"
  }, {
    path: "/ar/SalesOrder/pallet",
    component: _dcc539fc,
    name: "SalesOrder-pallet___ar"
  }, {
    path: "/ar/SalesOrder/Sales-create",
    component: _63d0d65f,
    name: "SalesOrder-Sales-create___ar"
  }, {
    path: "/ar/SalesOrder/Sales-list",
    component: _0d5e087e,
    name: "SalesOrder-Sales-list___ar"
  }, {
    path: "/ar/tables/advanced",
    component: _807e798a,
    name: "tables-advanced___ar"
  }, {
    path: "/ar/tables/basic",
    component: _fe003d8e,
    name: "tables-basic___ar"
  }, {
    path: "/ar/task/detail",
    component: _3ace9076,
    name: "task-detail___ar"
  }, {
    path: "/ar/task/kanban",
    component: _3f2e70a6,
    name: "task-kanban___ar"
  }, {
    path: "/ar/task/list",
    component: _dbdf4cfa,
    name: "task-list___ar"
  }, {
    path: "/ar/ui/avatars",
    component: _4f5130b6,
    name: "ui-avatars___ar"
  }, {
    path: "/ar/ui/buttons",
    component: _6276eb06,
    name: "ui-buttons___ar"
  }, {
    path: "/ar/ui/cards",
    component: _354ada5f,
    name: "ui-cards___ar"
  }, {
    path: "/ar/ui/carousel",
    component: _04e2bf94,
    name: "ui-carousel___ar"
  }, {
    path: "/ar/ui/dropdowns",
    component: _f4d61004,
    name: "ui-dropdowns___ar"
  }, {
    path: "/ar/ui/general",
    component: _6af9c864,
    name: "ui-general___ar"
  }, {
    path: "/ar/ui/grid",
    component: _eeac970c,
    name: "ui-grid___ar"
  }, {
    path: "/ar/ui/images",
    component: _74f668a8,
    name: "ui-images___ar"
  }, {
    path: "/ar/ui/list-group",
    component: _62371bc4,
    name: "ui-list-group___ar"
  }, {
    path: "/ar/ui/modals",
    component: _753904cc,
    name: "ui-modals___ar"
  }, {
    path: "/ar/ui/notifications",
    component: _056e1964,
    name: "ui-notifications___ar"
  }, {
    path: "/ar/ui/portlets",
    component: _01399b6d,
    name: "ui-portlets___ar"
  }, {
    path: "/ar/ui/progress",
    component: _6db81c3e,
    name: "ui-progress___ar"
  }, {
    path: "/ar/ui/ribbons",
    component: _220d194e,
    name: "ui-ribbons___ar"
  }, {
    path: "/ar/ui/spinners",
    component: _695c52ae,
    name: "ui-spinners___ar"
  }, {
    path: "/ar/ui/tabs-accordions",
    component: _77c67456,
    name: "ui-tabs-accordions___ar"
  }, {
    path: "/ar/ui/tooltips-popovers",
    component: _69f20872,
    name: "ui-tooltips-popovers___ar"
  }, {
    path: "/ar/ui/typography",
    component: _4a9fdce3,
    name: "ui-typography___ar"
  }, {
    path: "/ar/ui/video",
    component: _db648912,
    name: "ui-video___ar"
  }, {
    path: "/ar/widgets/data",
    component: _3d3f1d74,
    name: "widgets-data___ar"
  }, {
    path: "/charts/apex/data",
    component: _6b8880a4,
    name: "charts-apex-data___en"
  }, {
    path: "/charts/c3/data",
    component: _508b9dc0,
    name: "charts-c3-data___en"
  }, {
    path: "/charts/chartist/data",
    component: _6ac406a4,
    name: "charts-chartist-data___en"
  }, {
    path: "/charts/chartjs/BarChart",
    component: _3aff02ad,
    name: "charts-chartjs-BarChart___en"
  }, {
    path: "/charts/chartjs/DonutChart",
    component: _712a5404,
    name: "charts-chartjs-DonutChart___en"
  }, {
    path: "/charts/chartjs/LineChart",
    component: _8ff57dd0,
    name: "charts-chartjs-LineChart___en"
  }, {
    path: "/charts/chartjs/PieChart",
    component: _33be3558,
    name: "charts-chartjs-PieChart___en"
  }, {
    path: "/charts/chartjs/PolarChart",
    component: _7807b53c,
    name: "charts-chartjs-PolarChart___en"
  }, {
    path: "/charts/chartjs/RadarChart",
    component: _3f00329a,
    name: "charts-chartjs-RadarChart___en"
  }, {
    path: "/dashboard/analytics/channels",
    component: _cf93c43c,
    name: "dashboard-analytics-channels___en"
  }, {
    path: "/dashboard/analytics/overview",
    component: _422beb0b,
    name: "dashboard-analytics-overview___en"
  }, {
    path: "/dashboard/analytics/social-media",
    component: _76bd4896,
    name: "dashboard-analytics-social-media___en"
  }, {
    path: "/dashboard/analytics/sources",
    component: _538c2b96,
    name: "dashboard-analytics-sources___en"
  }, {
    path: "/dashboard/analytics/users",
    component: _564e0f66,
    name: "dashboard-analytics-users___en"
  }, {
    path: "/ecommerce/orders/data",
    component: _58166610,
    name: "ecommerce-orders-data___en"
  }, {
    path: "/ecommerce/products/data",
    component: _3bafc471,
    name: "ecommerce-products-data___en"
  }, {
    path: "/es/account/forgot-password",
    component: _0f022b18,
    name: "account-forgot-password___es"
  }, {
    path: "/es/account/login",
    component: _701e843c,
    name: "account-login___es"
  }, {
    path: "/es/account/register",
    component: _2d8f5b20,
    name: "account-register___es"
  }, {
    path: "/es/AccountManagement/accountConfig",
    component: _7e9f3882,
    name: "AccountManagement-accountConfig___es"
  }, {
    path: "/es/apps/calendar",
    component: _282012b2,
    name: "apps-calendar___es"
  }, {
    path: "/es/apps/chat",
    component: _0407cd50,
    name: "apps-chat___es"
  }, {
    path: "/es/apps/Companies",
    component: _f6cedd6e,
    name: "apps-Companies___es"
  }, {
    path: "/es/apps/file-manager",
    component: _6793bcee,
    name: "apps-file-manager___es"
  }, {
    path: "/es/charts/apex",
    component: _12774bcb,
    name: "charts-apex___es"
  }, {
    path: "/es/charts/c3",
    component: _8bc1ae86,
    name: "charts-c3___es"
  }, {
    path: "/es/charts/chartist",
    component: _9beca57e,
    name: "charts-chartist___es"
  }, {
    path: "/es/charts/chartjs",
    component: _0372c0c0,
    name: "charts-chartjs___es"
  }, {
    path: "/es/charts/knob",
    component: _a7db17aa,
    name: "charts-knob___es"
  }, {
    path: "/es/contacts/list",
    component: _a2b7525e,
    name: "contacts-list___es"
  }, {
    path: "/es/contacts/profile",
    component: _501f0346,
    name: "contacts-profile___es"
  }, {
    path: "/es/Customers/data",
    component: _58949880,
    name: "Customers-data___es"
  }, {
    path: "/es/dashboard/analytics",
    component: _10e43530,
    name: "dashboard-analytics___es"
  }, {
    path: "/es/dashboard/crm",
    component: _0038fe50,
    name: "dashboard-crm___es"
  }, {
    path: "/es/dashboard/sales",
    component: _18ccc42c,
    name: "dashboard-sales___es"
  }, {
    path: "/es/ecommerce/cart",
    component: _2291cdf0,
    name: "ecommerce-cart___es"
  }, {
    path: "/es/ecommerce/checkout",
    component: _2d4b7dd4,
    name: "ecommerce-checkout___es"
  }, {
    path: "/es/ecommerce/data-products",
    component: _ccadeeb0,
    name: "ecommerce-data-products___es"
  }, {
    path: "/es/ecommerce/order-detail",
    component: _38c99a80,
    name: "ecommerce-order-detail___es"
  }, {
    path: "/es/ecommerce/orders",
    component: _d77c3ca6,
    name: "ecommerce-orders___es"
  }, {
    path: "/es/ecommerce/product-create",
    component: _57bd436a,
    name: "ecommerce-product-create___es"
  }, {
    path: "/es/ecommerce/products",
    component: _1205a864,
    name: "ecommerce-products___es"
  }, {
    path: "/es/ecommerce/products-grid",
    component: _6b12bbef,
    name: "ecommerce-products-grid___es"
  }, {
    path: "/es/ecommerce/sellers",
    component: _baade398,
    name: "ecommerce-sellers___es"
  }, {
    path: "/es/ecommerce/Variant-product-create",
    component: _805cb45c,
    name: "ecommerce-Variant-product-create___es"
  }, {
    path: "/es/email/data-inbox",
    component: _56d01260,
    name: "email-data-inbox___es"
  }, {
    path: "/es/email/inbox",
    component: _7553360a,
    name: "email-inbox___es"
  }, {
    path: "/es/email/sidepanel",
    component: _b6cee5de,
    name: "email-sidepanel___es"
  }, {
    path: "/es/email/templates",
    component: _1c3d6f3d,
    name: "email-templates___es"
  }, {
    path: "/es/email/toolbar",
    component: _3b925d02,
    name: "email-toolbar___es"
  }, {
    path: "/es/extras/404",
    component: _99712076,
    name: "extras-404___es"
  }, {
    path: "/es/extras/404-alt",
    component: _119a71a1,
    name: "extras-404-alt___es"
  }, {
    path: "/es/extras/500",
    component: _301565fc,
    name: "extras-500___es"
  }, {
    path: "/es/extras/coming-soon",
    component: _22740ed4,
    name: "extras-coming-soon___es"
  }, {
    path: "/es/extras/faqs",
    component: _e9143a40,
    name: "extras-faqs___es"
  }, {
    path: "/es/extras/invoice",
    component: _b11c368c,
    name: "extras-invoice___es"
  }, {
    path: "/es/extras/lightbox",
    component: _6e04ba38,
    name: "extras-lightbox___es"
  }, {
    path: "/es/extras/maintenance",
    component: _59c66f20,
    name: "extras-maintenance___es"
  }, {
    path: "/es/extras/pricing",
    component: _37b24cd3,
    name: "extras-pricing___es"
  }, {
    path: "/es/extras/search-results",
    component: _26bcd3d4,
    name: "extras-search-results___es"
  }, {
    path: "/es/extras/sitemap",
    component: _4c674a42,
    name: "extras-sitemap___es"
  }, {
    path: "/es/extras/starter",
    component: _ebb53dc8,
    name: "extras-starter___es"
  }, {
    path: "/es/extras/timeline",
    component: _4e0240f8,
    name: "extras-timeline___es"
  }, {
    path: "/es/Finance/BalanceTransaction",
    component: _73b4d7cc,
    name: "Finance-BalanceTransaction___es"
  }, {
    path: "/es/Finance/CompanyFile",
    component: _35c06a1f,
    name: "Finance-CompanyFile___es"
  }, {
    path: "/es/Finance/Invoices",
    component: _6c42ecd0,
    name: "Finance-Invoices___es"
  }, {
    path: "/es/Finance/Payments",
    component: _f26544d2,
    name: "Finance-Payments___es"
  }, {
    path: "/es/forms/advanced",
    component: _c3da5cbe,
    name: "forms-advanced___es"
  }, {
    path: "/es/forms/elements",
    component: _508c9014,
    name: "forms-elements___es"
  }, {
    path: "/es/forms/file-uploads",
    component: _720bc5c0,
    name: "forms-file-uploads___es"
  }, {
    path: "/es/forms/mask",
    component: _461c06eb,
    name: "forms-mask___es"
  }, {
    path: "/es/forms/quill",
    component: _3fe4ced4,
    name: "forms-quill___es"
  }, {
    path: "/es/forms/validation",
    component: _542650b8,
    name: "forms-validation___es"
  }, {
    path: "/es/forms/wizard",
    component: _d5649fac,
    name: "forms-wizard___es"
  }, {
    path: "/es/icons/boxicons",
    component: _674fb24e,
    name: "icons-boxicons___es"
  }, {
    path: "/es/icons/data-fontawesome",
    component: _665b14f4,
    name: "icons-data-fontawesome___es"
  }, {
    path: "/es/icons/data-material",
    component: _a42bdf42,
    name: "icons-data-material___es"
  }, {
    path: "/es/icons/data-remix",
    component: _483b9f7f,
    name: "icons-data-remix___es"
  }, {
    path: "/es/icons/feather",
    component: _6b59602e,
    name: "icons-feather___es"
  }, {
    path: "/es/icons/font-awesome",
    component: _2db7978f,
    name: "icons-font-awesome___es"
  }, {
    path: "/es/icons/mdi",
    component: _ef3c5710,
    name: "icons-mdi___es"
  }, {
    path: "/es/icons/remix",
    component: _7cb8ff0f,
    name: "icons-remix___es"
  }, {
    path: "/es/icons/weather",
    component: _a4f9a28c,
    name: "icons-weather___es"
  }, {
    path: "/es/Inventory/Inventory-list",
    component: _700148db,
    name: "Inventory-Inventory-list___es"
  }, {
    path: "/es/maps/google",
    component: _7ed72f20,
    name: "maps-google___es"
  }, {
    path: "/es/PurchaseOrders/data",
    component: _33fd505f,
    name: "PurchaseOrders-data___es"
  }, {
    path: "/es/PurchaseOrders/order-detail",
    component: _6e218036,
    name: "PurchaseOrders-order-detail___es"
  }, {
    path: "/es/PurchaseOrders/order-list",
    component: _48dc3943,
    name: "PurchaseOrders-order-list___es"
  }, {
    path: "/es/PurchaseOrders/Purchase-create",
    component: _1a6c45dc,
    name: "PurchaseOrders-Purchase-create___es"
  }, {
    path: "/es/SalesOrder/pallet",
    component: _dcc539fc,
    name: "SalesOrder-pallet___es"
  }, {
    path: "/es/SalesOrder/Sales-create",
    component: _63d0d65f,
    name: "SalesOrder-Sales-create___es"
  }, {
    path: "/es/SalesOrder/Sales-list",
    component: _0d5e087e,
    name: "SalesOrder-Sales-list___es"
  }, {
    path: "/es/tables/advanced",
    component: _807e798a,
    name: "tables-advanced___es"
  }, {
    path: "/es/tables/basic",
    component: _fe003d8e,
    name: "tables-basic___es"
  }, {
    path: "/es/task/detail",
    component: _3ace9076,
    name: "task-detail___es"
  }, {
    path: "/es/task/kanban",
    component: _3f2e70a6,
    name: "task-kanban___es"
  }, {
    path: "/es/task/list",
    component: _dbdf4cfa,
    name: "task-list___es"
  }, {
    path: "/es/ui/avatars",
    component: _4f5130b6,
    name: "ui-avatars___es"
  }, {
    path: "/es/ui/buttons",
    component: _6276eb06,
    name: "ui-buttons___es"
  }, {
    path: "/es/ui/cards",
    component: _354ada5f,
    name: "ui-cards___es"
  }, {
    path: "/es/ui/carousel",
    component: _04e2bf94,
    name: "ui-carousel___es"
  }, {
    path: "/es/ui/dropdowns",
    component: _f4d61004,
    name: "ui-dropdowns___es"
  }, {
    path: "/es/ui/general",
    component: _6af9c864,
    name: "ui-general___es"
  }, {
    path: "/es/ui/grid",
    component: _eeac970c,
    name: "ui-grid___es"
  }, {
    path: "/es/ui/images",
    component: _74f668a8,
    name: "ui-images___es"
  }, {
    path: "/es/ui/list-group",
    component: _62371bc4,
    name: "ui-list-group___es"
  }, {
    path: "/es/ui/modals",
    component: _753904cc,
    name: "ui-modals___es"
  }, {
    path: "/es/ui/notifications",
    component: _056e1964,
    name: "ui-notifications___es"
  }, {
    path: "/es/ui/portlets",
    component: _01399b6d,
    name: "ui-portlets___es"
  }, {
    path: "/es/ui/progress",
    component: _6db81c3e,
    name: "ui-progress___es"
  }, {
    path: "/es/ui/ribbons",
    component: _220d194e,
    name: "ui-ribbons___es"
  }, {
    path: "/es/ui/spinners",
    component: _695c52ae,
    name: "ui-spinners___es"
  }, {
    path: "/es/ui/tabs-accordions",
    component: _77c67456,
    name: "ui-tabs-accordions___es"
  }, {
    path: "/es/ui/tooltips-popovers",
    component: _69f20872,
    name: "ui-tooltips-popovers___es"
  }, {
    path: "/es/ui/typography",
    component: _4a9fdce3,
    name: "ui-typography___es"
  }, {
    path: "/es/ui/video",
    component: _db648912,
    name: "ui-video___es"
  }, {
    path: "/es/widgets/data",
    component: _3d3f1d74,
    name: "widgets-data___es"
  }, {
    path: "/Finance/Expenses/Expense",
    component: _1d495e03,
    name: "Finance-Expenses-Expense___en"
  }, {
    path: "/Finance/Expenses/list-Expenses",
    component: _757843d6,
    name: "Finance-Expenses-list-Expenses___en"
  }, {
    path: "/fr/account/forgot-password",
    component: _0f022b18,
    name: "account-forgot-password___fr"
  }, {
    path: "/fr/account/login",
    component: _701e843c,
    name: "account-login___fr"
  }, {
    path: "/fr/account/register",
    component: _2d8f5b20,
    name: "account-register___fr"
  }, {
    path: "/fr/AccountManagement/accountConfig",
    component: _7e9f3882,
    name: "AccountManagement-accountConfig___fr"
  }, {
    path: "/fr/apps/calendar",
    component: _282012b2,
    name: "apps-calendar___fr"
  }, {
    path: "/fr/apps/chat",
    component: _0407cd50,
    name: "apps-chat___fr"
  }, {
    path: "/fr/apps/Companies",
    component: _f6cedd6e,
    name: "apps-Companies___fr"
  }, {
    path: "/fr/apps/file-manager",
    component: _6793bcee,
    name: "apps-file-manager___fr"
  }, {
    path: "/fr/charts/apex",
    component: _12774bcb,
    name: "charts-apex___fr"
  }, {
    path: "/fr/charts/c3",
    component: _8bc1ae86,
    name: "charts-c3___fr"
  }, {
    path: "/fr/charts/chartist",
    component: _9beca57e,
    name: "charts-chartist___fr"
  }, {
    path: "/fr/charts/chartjs",
    component: _0372c0c0,
    name: "charts-chartjs___fr"
  }, {
    path: "/fr/charts/knob",
    component: _a7db17aa,
    name: "charts-knob___fr"
  }, {
    path: "/fr/contacts/list",
    component: _a2b7525e,
    name: "contacts-list___fr"
  }, {
    path: "/fr/contacts/profile",
    component: _501f0346,
    name: "contacts-profile___fr"
  }, {
    path: "/fr/Customers/data",
    component: _58949880,
    name: "Customers-data___fr"
  }, {
    path: "/fr/dashboard/analytics",
    component: _10e43530,
    name: "dashboard-analytics___fr"
  }, {
    path: "/fr/dashboard/crm",
    component: _0038fe50,
    name: "dashboard-crm___fr"
  }, {
    path: "/fr/dashboard/sales",
    component: _18ccc42c,
    name: "dashboard-sales___fr"
  }, {
    path: "/fr/ecommerce/cart",
    component: _2291cdf0,
    name: "ecommerce-cart___fr"
  }, {
    path: "/fr/ecommerce/checkout",
    component: _2d4b7dd4,
    name: "ecommerce-checkout___fr"
  }, {
    path: "/fr/ecommerce/data-products",
    component: _ccadeeb0,
    name: "ecommerce-data-products___fr"
  }, {
    path: "/fr/ecommerce/order-detail",
    component: _38c99a80,
    name: "ecommerce-order-detail___fr"
  }, {
    path: "/fr/ecommerce/orders",
    component: _d77c3ca6,
    name: "ecommerce-orders___fr"
  }, {
    path: "/fr/ecommerce/product-create",
    component: _57bd436a,
    name: "ecommerce-product-create___fr"
  }, {
    path: "/fr/ecommerce/products",
    component: _1205a864,
    name: "ecommerce-products___fr"
  }, {
    path: "/fr/ecommerce/products-grid",
    component: _6b12bbef,
    name: "ecommerce-products-grid___fr"
  }, {
    path: "/fr/ecommerce/sellers",
    component: _baade398,
    name: "ecommerce-sellers___fr"
  }, {
    path: "/fr/ecommerce/Variant-product-create",
    component: _805cb45c,
    name: "ecommerce-Variant-product-create___fr"
  }, {
    path: "/fr/email/data-inbox",
    component: _56d01260,
    name: "email-data-inbox___fr"
  }, {
    path: "/fr/email/inbox",
    component: _7553360a,
    name: "email-inbox___fr"
  }, {
    path: "/fr/email/sidepanel",
    component: _b6cee5de,
    name: "email-sidepanel___fr"
  }, {
    path: "/fr/email/templates",
    component: _1c3d6f3d,
    name: "email-templates___fr"
  }, {
    path: "/fr/email/toolbar",
    component: _3b925d02,
    name: "email-toolbar___fr"
  }, {
    path: "/fr/extras/404",
    component: _99712076,
    name: "extras-404___fr"
  }, {
    path: "/fr/extras/404-alt",
    component: _119a71a1,
    name: "extras-404-alt___fr"
  }, {
    path: "/fr/extras/500",
    component: _301565fc,
    name: "extras-500___fr"
  }, {
    path: "/fr/extras/coming-soon",
    component: _22740ed4,
    name: "extras-coming-soon___fr"
  }, {
    path: "/fr/extras/faqs",
    component: _e9143a40,
    name: "extras-faqs___fr"
  }, {
    path: "/fr/extras/invoice",
    component: _b11c368c,
    name: "extras-invoice___fr"
  }, {
    path: "/fr/extras/lightbox",
    component: _6e04ba38,
    name: "extras-lightbox___fr"
  }, {
    path: "/fr/extras/maintenance",
    component: _59c66f20,
    name: "extras-maintenance___fr"
  }, {
    path: "/fr/extras/pricing",
    component: _37b24cd3,
    name: "extras-pricing___fr"
  }, {
    path: "/fr/extras/search-results",
    component: _26bcd3d4,
    name: "extras-search-results___fr"
  }, {
    path: "/fr/extras/sitemap",
    component: _4c674a42,
    name: "extras-sitemap___fr"
  }, {
    path: "/fr/extras/starter",
    component: _ebb53dc8,
    name: "extras-starter___fr"
  }, {
    path: "/fr/extras/timeline",
    component: _4e0240f8,
    name: "extras-timeline___fr"
  }, {
    path: "/fr/Finance/BalanceTransaction",
    component: _73b4d7cc,
    name: "Finance-BalanceTransaction___fr"
  }, {
    path: "/fr/Finance/CompanyFile",
    component: _35c06a1f,
    name: "Finance-CompanyFile___fr"
  }, {
    path: "/fr/Finance/Invoices",
    component: _6c42ecd0,
    name: "Finance-Invoices___fr"
  }, {
    path: "/fr/Finance/Payments",
    component: _f26544d2,
    name: "Finance-Payments___fr"
  }, {
    path: "/fr/forms/advanced",
    component: _c3da5cbe,
    name: "forms-advanced___fr"
  }, {
    path: "/fr/forms/elements",
    component: _508c9014,
    name: "forms-elements___fr"
  }, {
    path: "/fr/forms/file-uploads",
    component: _720bc5c0,
    name: "forms-file-uploads___fr"
  }, {
    path: "/fr/forms/mask",
    component: _461c06eb,
    name: "forms-mask___fr"
  }, {
    path: "/fr/forms/quill",
    component: _3fe4ced4,
    name: "forms-quill___fr"
  }, {
    path: "/fr/forms/validation",
    component: _542650b8,
    name: "forms-validation___fr"
  }, {
    path: "/fr/forms/wizard",
    component: _d5649fac,
    name: "forms-wizard___fr"
  }, {
    path: "/fr/icons/boxicons",
    component: _674fb24e,
    name: "icons-boxicons___fr"
  }, {
    path: "/fr/icons/data-fontawesome",
    component: _665b14f4,
    name: "icons-data-fontawesome___fr"
  }, {
    path: "/fr/icons/data-material",
    component: _a42bdf42,
    name: "icons-data-material___fr"
  }, {
    path: "/fr/icons/data-remix",
    component: _483b9f7f,
    name: "icons-data-remix___fr"
  }, {
    path: "/fr/icons/feather",
    component: _6b59602e,
    name: "icons-feather___fr"
  }, {
    path: "/fr/icons/font-awesome",
    component: _2db7978f,
    name: "icons-font-awesome___fr"
  }, {
    path: "/fr/icons/mdi",
    component: _ef3c5710,
    name: "icons-mdi___fr"
  }, {
    path: "/fr/icons/remix",
    component: _7cb8ff0f,
    name: "icons-remix___fr"
  }, {
    path: "/fr/icons/weather",
    component: _a4f9a28c,
    name: "icons-weather___fr"
  }, {
    path: "/fr/Inventory/Inventory-list",
    component: _700148db,
    name: "Inventory-Inventory-list___fr"
  }, {
    path: "/fr/maps/google",
    component: _7ed72f20,
    name: "maps-google___fr"
  }, {
    path: "/fr/PurchaseOrders/data",
    component: _33fd505f,
    name: "PurchaseOrders-data___fr"
  }, {
    path: "/fr/PurchaseOrders/order-detail",
    component: _6e218036,
    name: "PurchaseOrders-order-detail___fr"
  }, {
    path: "/fr/PurchaseOrders/order-list",
    component: _48dc3943,
    name: "PurchaseOrders-order-list___fr"
  }, {
    path: "/fr/PurchaseOrders/Purchase-create",
    component: _1a6c45dc,
    name: "PurchaseOrders-Purchase-create___fr"
  }, {
    path: "/fr/SalesOrder/pallet",
    component: _dcc539fc,
    name: "SalesOrder-pallet___fr"
  }, {
    path: "/fr/SalesOrder/Sales-create",
    component: _63d0d65f,
    name: "SalesOrder-Sales-create___fr"
  }, {
    path: "/fr/SalesOrder/Sales-list",
    component: _0d5e087e,
    name: "SalesOrder-Sales-list___fr"
  }, {
    path: "/fr/tables/advanced",
    component: _807e798a,
    name: "tables-advanced___fr"
  }, {
    path: "/fr/tables/basic",
    component: _fe003d8e,
    name: "tables-basic___fr"
  }, {
    path: "/fr/task/detail",
    component: _3ace9076,
    name: "task-detail___fr"
  }, {
    path: "/fr/task/kanban",
    component: _3f2e70a6,
    name: "task-kanban___fr"
  }, {
    path: "/fr/task/list",
    component: _dbdf4cfa,
    name: "task-list___fr"
  }, {
    path: "/fr/ui/avatars",
    component: _4f5130b6,
    name: "ui-avatars___fr"
  }, {
    path: "/fr/ui/buttons",
    component: _6276eb06,
    name: "ui-buttons___fr"
  }, {
    path: "/fr/ui/cards",
    component: _354ada5f,
    name: "ui-cards___fr"
  }, {
    path: "/fr/ui/carousel",
    component: _04e2bf94,
    name: "ui-carousel___fr"
  }, {
    path: "/fr/ui/dropdowns",
    component: _f4d61004,
    name: "ui-dropdowns___fr"
  }, {
    path: "/fr/ui/general",
    component: _6af9c864,
    name: "ui-general___fr"
  }, {
    path: "/fr/ui/grid",
    component: _eeac970c,
    name: "ui-grid___fr"
  }, {
    path: "/fr/ui/images",
    component: _74f668a8,
    name: "ui-images___fr"
  }, {
    path: "/fr/ui/list-group",
    component: _62371bc4,
    name: "ui-list-group___fr"
  }, {
    path: "/fr/ui/modals",
    component: _753904cc,
    name: "ui-modals___fr"
  }, {
    path: "/fr/ui/notifications",
    component: _056e1964,
    name: "ui-notifications___fr"
  }, {
    path: "/fr/ui/portlets",
    component: _01399b6d,
    name: "ui-portlets___fr"
  }, {
    path: "/fr/ui/progress",
    component: _6db81c3e,
    name: "ui-progress___fr"
  }, {
    path: "/fr/ui/ribbons",
    component: _220d194e,
    name: "ui-ribbons___fr"
  }, {
    path: "/fr/ui/spinners",
    component: _695c52ae,
    name: "ui-spinners___fr"
  }, {
    path: "/fr/ui/tabs-accordions",
    component: _77c67456,
    name: "ui-tabs-accordions___fr"
  }, {
    path: "/fr/ui/tooltips-popovers",
    component: _69f20872,
    name: "ui-tooltips-popovers___fr"
  }, {
    path: "/fr/ui/typography",
    component: _4a9fdce3,
    name: "ui-typography___fr"
  }, {
    path: "/fr/ui/video",
    component: _db648912,
    name: "ui-video___fr"
  }, {
    path: "/fr/widgets/data",
    component: _3d3f1d74,
    name: "widgets-data___fr"
  }, {
    path: "/tables/advanced/data",
    component: _854759c4,
    name: "tables-advanced-data___en"
  }, {
    path: "/task/kanban/data",
    component: _0c9c5f49,
    name: "task-kanban-data___en"
  }, {
    path: "/ar/apps/calendar/data-calendar",
    component: _a72ee1e4,
    name: "apps-calendar-data-calendar___ar"
  }, {
    path: "/ar/apps/chat/data",
    component: _03c08c7b,
    name: "apps-chat-data___ar"
  }, {
    path: "/ar/apps/Companies/data",
    component: _036766a8,
    name: "apps-Companies-data___ar"
  }, {
    path: "/ar/charts/apex/data",
    component: _6b8880a4,
    name: "charts-apex-data___ar"
  }, {
    path: "/ar/charts/c3/data",
    component: _508b9dc0,
    name: "charts-c3-data___ar"
  }, {
    path: "/ar/charts/chartist/data",
    component: _6ac406a4,
    name: "charts-chartist-data___ar"
  }, {
    path: "/ar/charts/chartjs/BarChart",
    component: _3aff02ad,
    name: "charts-chartjs-BarChart___ar"
  }, {
    path: "/ar/charts/chartjs/DonutChart",
    component: _712a5404,
    name: "charts-chartjs-DonutChart___ar"
  }, {
    path: "/ar/charts/chartjs/LineChart",
    component: _8ff57dd0,
    name: "charts-chartjs-LineChart___ar"
  }, {
    path: "/ar/charts/chartjs/PieChart",
    component: _33be3558,
    name: "charts-chartjs-PieChart___ar"
  }, {
    path: "/ar/charts/chartjs/PolarChart",
    component: _7807b53c,
    name: "charts-chartjs-PolarChart___ar"
  }, {
    path: "/ar/charts/chartjs/RadarChart",
    component: _3f00329a,
    name: "charts-chartjs-RadarChart___ar"
  }, {
    path: "/ar/dashboard/analytics/channels",
    component: _cf93c43c,
    name: "dashboard-analytics-channels___ar"
  }, {
    path: "/ar/dashboard/analytics/overview",
    component: _422beb0b,
    name: "dashboard-analytics-overview___ar"
  }, {
    path: "/ar/dashboard/analytics/social-media",
    component: _76bd4896,
    name: "dashboard-analytics-social-media___ar"
  }, {
    path: "/ar/dashboard/analytics/sources",
    component: _538c2b96,
    name: "dashboard-analytics-sources___ar"
  }, {
    path: "/ar/dashboard/analytics/users",
    component: _564e0f66,
    name: "dashboard-analytics-users___ar"
  }, {
    path: "/ar/ecommerce/orders/data",
    component: _58166610,
    name: "ecommerce-orders-data___ar"
  }, {
    path: "/ar/ecommerce/products/data",
    component: _3bafc471,
    name: "ecommerce-products-data___ar"
  }, {
    path: "/ar/Finance/Expenses/Expense",
    component: _1d495e03,
    name: "Finance-Expenses-Expense___ar"
  }, {
    path: "/ar/Finance/Expenses/list-Expenses",
    component: _757843d6,
    name: "Finance-Expenses-list-Expenses___ar"
  }, {
    path: "/ar/tables/advanced/data",
    component: _854759c4,
    name: "tables-advanced-data___ar"
  }, {
    path: "/ar/task/kanban/data",
    component: _0c9c5f49,
    name: "task-kanban-data___ar"
  }, {
    path: "/es/apps/calendar/data-calendar",
    component: _a72ee1e4,
    name: "apps-calendar-data-calendar___es"
  }, {
    path: "/es/apps/chat/data",
    component: _03c08c7b,
    name: "apps-chat-data___es"
  }, {
    path: "/es/apps/Companies/data",
    component: _036766a8,
    name: "apps-Companies-data___es"
  }, {
    path: "/es/charts/apex/data",
    component: _6b8880a4,
    name: "charts-apex-data___es"
  }, {
    path: "/es/charts/c3/data",
    component: _508b9dc0,
    name: "charts-c3-data___es"
  }, {
    path: "/es/charts/chartist/data",
    component: _6ac406a4,
    name: "charts-chartist-data___es"
  }, {
    path: "/es/charts/chartjs/BarChart",
    component: _3aff02ad,
    name: "charts-chartjs-BarChart___es"
  }, {
    path: "/es/charts/chartjs/DonutChart",
    component: _712a5404,
    name: "charts-chartjs-DonutChart___es"
  }, {
    path: "/es/charts/chartjs/LineChart",
    component: _8ff57dd0,
    name: "charts-chartjs-LineChart___es"
  }, {
    path: "/es/charts/chartjs/PieChart",
    component: _33be3558,
    name: "charts-chartjs-PieChart___es"
  }, {
    path: "/es/charts/chartjs/PolarChart",
    component: _7807b53c,
    name: "charts-chartjs-PolarChart___es"
  }, {
    path: "/es/charts/chartjs/RadarChart",
    component: _3f00329a,
    name: "charts-chartjs-RadarChart___es"
  }, {
    path: "/es/dashboard/analytics/channels",
    component: _cf93c43c,
    name: "dashboard-analytics-channels___es"
  }, {
    path: "/es/dashboard/analytics/overview",
    component: _422beb0b,
    name: "dashboard-analytics-overview___es"
  }, {
    path: "/es/dashboard/analytics/social-media",
    component: _76bd4896,
    name: "dashboard-analytics-social-media___es"
  }, {
    path: "/es/dashboard/analytics/sources",
    component: _538c2b96,
    name: "dashboard-analytics-sources___es"
  }, {
    path: "/es/dashboard/analytics/users",
    component: _564e0f66,
    name: "dashboard-analytics-users___es"
  }, {
    path: "/es/ecommerce/orders/data",
    component: _58166610,
    name: "ecommerce-orders-data___es"
  }, {
    path: "/es/ecommerce/products/data",
    component: _3bafc471,
    name: "ecommerce-products-data___es"
  }, {
    path: "/es/Finance/Expenses/Expense",
    component: _1d495e03,
    name: "Finance-Expenses-Expense___es"
  }, {
    path: "/es/Finance/Expenses/list-Expenses",
    component: _757843d6,
    name: "Finance-Expenses-list-Expenses___es"
  }, {
    path: "/es/tables/advanced/data",
    component: _854759c4,
    name: "tables-advanced-data___es"
  }, {
    path: "/es/task/kanban/data",
    component: _0c9c5f49,
    name: "task-kanban-data___es"
  }, {
    path: "/fr/apps/calendar/data-calendar",
    component: _a72ee1e4,
    name: "apps-calendar-data-calendar___fr"
  }, {
    path: "/fr/apps/chat/data",
    component: _03c08c7b,
    name: "apps-chat-data___fr"
  }, {
    path: "/fr/apps/Companies/data",
    component: _036766a8,
    name: "apps-Companies-data___fr"
  }, {
    path: "/fr/charts/apex/data",
    component: _6b8880a4,
    name: "charts-apex-data___fr"
  }, {
    path: "/fr/charts/c3/data",
    component: _508b9dc0,
    name: "charts-c3-data___fr"
  }, {
    path: "/fr/charts/chartist/data",
    component: _6ac406a4,
    name: "charts-chartist-data___fr"
  }, {
    path: "/fr/charts/chartjs/BarChart",
    component: _3aff02ad,
    name: "charts-chartjs-BarChart___fr"
  }, {
    path: "/fr/charts/chartjs/DonutChart",
    component: _712a5404,
    name: "charts-chartjs-DonutChart___fr"
  }, {
    path: "/fr/charts/chartjs/LineChart",
    component: _8ff57dd0,
    name: "charts-chartjs-LineChart___fr"
  }, {
    path: "/fr/charts/chartjs/PieChart",
    component: _33be3558,
    name: "charts-chartjs-PieChart___fr"
  }, {
    path: "/fr/charts/chartjs/PolarChart",
    component: _7807b53c,
    name: "charts-chartjs-PolarChart___fr"
  }, {
    path: "/fr/charts/chartjs/RadarChart",
    component: _3f00329a,
    name: "charts-chartjs-RadarChart___fr"
  }, {
    path: "/fr/dashboard/analytics/channels",
    component: _cf93c43c,
    name: "dashboard-analytics-channels___fr"
  }, {
    path: "/fr/dashboard/analytics/overview",
    component: _422beb0b,
    name: "dashboard-analytics-overview___fr"
  }, {
    path: "/fr/dashboard/analytics/social-media",
    component: _76bd4896,
    name: "dashboard-analytics-social-media___fr"
  }, {
    path: "/fr/dashboard/analytics/sources",
    component: _538c2b96,
    name: "dashboard-analytics-sources___fr"
  }, {
    path: "/fr/dashboard/analytics/users",
    component: _564e0f66,
    name: "dashboard-analytics-users___fr"
  }, {
    path: "/fr/ecommerce/orders/data",
    component: _58166610,
    name: "ecommerce-orders-data___fr"
  }, {
    path: "/fr/ecommerce/products/data",
    component: _3bafc471,
    name: "ecommerce-products-data___fr"
  }, {
    path: "/fr/Finance/Expenses/Expense",
    component: _1d495e03,
    name: "Finance-Expenses-Expense___fr"
  }, {
    path: "/fr/Finance/Expenses/list-Expenses",
    component: _757843d6,
    name: "Finance-Expenses-list-Expenses___fr"
  }, {
    path: "/fr/tables/advanced/data",
    component: _854759c4,
    name: "tables-advanced-data___fr"
  }, {
    path: "/fr/task/kanban/data",
    component: _0c9c5f49,
    name: "task-kanban-data___fr"
  }, {
    path: "/ar/ecommerce/product-detail/:id?",
    component: _890c52ea,
    name: "ecommerce-product-detail-id___ar"
  }, {
    path: "/ar/email/reademail/:id?",
    component: _2e293060,
    name: "email-reademail-id___ar"
  }, {
    path: "/es/ecommerce/product-detail/:id?",
    component: _890c52ea,
    name: "ecommerce-product-detail-id___es"
  }, {
    path: "/es/email/reademail/:id?",
    component: _2e293060,
    name: "email-reademail-id___es"
  }, {
    path: "/fr/ecommerce/product-detail/:id?",
    component: _890c52ea,
    name: "ecommerce-product-detail-id___fr"
  }, {
    path: "/fr/email/reademail/:id?",
    component: _2e293060,
    name: "email-reademail-id___fr"
  }, {
    path: "/ecommerce/product-detail/:id?",
    component: _890c52ea,
    name: "ecommerce-product-detail-id___en"
  }, {
    path: "/email/reademail/:id?",
    component: _2e293060,
    name: "email-reademail-id___en"
  }, {
    path: "/",
    component: _7a6dbb4c
  }],

  fallback: false
}

export function createRouter () {
  return new Router(routerOptions)
}
